"""Orchestrator — runs all agents in parallel and bundles output as a mkdocs site."""

import asyncio
from dataclasses import dataclass, field
from pathlib import Path

import yaml
from openai import AsyncOpenAI

from docsforge.core.agent import AgentOutput
from docsforge.core.scanner import RepoMeta
from docsforge.agents.architecture import ArchitectureAgent
from docsforge.agents.api import APIAgent
from docsforge.agents.examples import ExamplesAgent
from docsforge.agents.changelog import ChangelogAgent
from docsforge.agents.config import ConfigAgent


@dataclass
class BuildResult:
    """Result of a docs build."""
    repo_name: str
    output_dir: str
    agent_outputs: list[AgentOutput] = field(default_factory=list)
    total_tokens: int = 0
    pages_generated: int = 0
    errors: list[str] = field(default_factory=list)


class Orchestrator:
    """Coordinates all agents and assembles the final mkdocs site."""

    def __init__(self, client: AsyncOpenAI, model: str):
        self.client = client
        self.model = model
        self.agents = [
            ArchitectureAgent(client, model),
            APIAgent(client, model),
            ExamplesAgent(client, model),
            ChangelogAgent(client, model),
            ConfigAgent(client, model),
        ]

    async def build(self, meta: RepoMeta, output_dir: str | Path) -> BuildResult:
        """Run all agents in parallel and write a mkdocs site bundle."""
        out = Path(output_dir).resolve()
        docs_dir = out / "docs"
        docs_dir.mkdir(parents=True, exist_ok=True)

        result = BuildResult(repo_name=meta.name, output_dir=str(out))

        # Fan out
        tasks = [agent.run(meta) for agent in self.agents]
        outputs = await asyncio.gather(*tasks, return_exceptions=True)

        nav_entries: list[dict] = []
        for i, output in enumerate(outputs):
            agent_name = self.agents[i].config.name
            if isinstance(output, Exception):
                result.errors.append(f"{agent_name}: {output}")
                continue

            result.agent_outputs.append(output)
            result.total_tokens += output.tokens_used

            for filename, content in output.pages.items():
                page_path = docs_dir / filename
                page_path.write_text(content, encoding="utf-8")
                result.pages_generated += 1

                # Build nav entry from filename
                title = _filename_to_title(filename)
                nav_entries.append({title: filename})

        # Write index page
        index_md = _build_index(meta, result, nav_entries)
        (docs_dir / "index.md").write_text(index_md, encoding="utf-8")

        # Build mkdocs.yml
        mkdocs_config = {
            "site_name": f"{meta.name} — Documentation",
            "site_description": "Auto-generated by DocsForge",
            "theme": {
                "name": "material",
                "palette": [
                    {"scheme": "slate", "primary": "deep purple", "accent": "purple"},
                ],
                "features": ["navigation.tabs", "navigation.sections", "content.code.copy"],
            },
            "nav": [{"Home": "index.md"}] + nav_entries,
            "markdown_extensions": [
                "fenced_code",
                "tables",
                "admonition",
                "codehilite",
                {"toc": {"permalink": True}},
                {"pymdownx.superfences": {
                    "custom_fences": [
                        {"name": "mermaid", "class": "mermaid",
                         "format": "!!python/name:pymdownx.superfences.fence_code_format"},
                    ],
                }},
            ],
        }
        # Use safe_dump but allow our format string for mermaid
        mkdocs_yml = yaml.safe_dump(mkdocs_config, sort_keys=False, default_flow_style=False)
        # Patch in the python/name reference (yaml safe_dump won't keep it)
        mkdocs_yml = mkdocs_yml.replace(
            "format: '!!python/name:pymdownx.superfences.fence_code_format'",
            "format: !!python/name:pymdownx.superfences.fence_code_format",
        )
        (out / "mkdocs.yml").write_text(mkdocs_yml, encoding="utf-8")

        return result


def _filename_to_title(filename: str) -> str:
    base = filename.rsplit(".", 1)[0]
    return base.replace("-", " ").replace("_", " ").title()


def _build_index(meta: RepoMeta, result: BuildResult, nav: list[dict]) -> str:
    pages = "\n".join(f"- [{list(n.keys())[0]}]({list(n.values())[0]})" for n in nav)
    return f"""# {meta.name}

Auto-generated documentation for **{meta.name}**.

> Built by DocsForge — multi-agent documentation pipeline.

## Pages

{pages}

## Repo Stats

- Total files scanned: {len(meta.files)}
- Languages: {', '.join(meta.languages.keys()) or 'none'}
- Total LOC: {meta.total_loc}
- Public Python symbols: {len(meta.python_symbols)}

## Build Stats

- Pages generated: {result.pages_generated}
- Tokens used: {result.total_tokens:,}
- Agents run: {len(result.agent_outputs)} / {len(nav)}
- Errors: {len(result.errors)}
"""
